# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c7cb7307d8dc47bf060a549f754c91115f38d58b76201d3df3af58ead990a4e1da3d8efa87d737ae95ef289cd4c5af44e95d912560815e9bc8b413f134f5836

test:
  secret_key_base: 972ee46411f8b90e61a26509dab6aee02e2716d15d72da98d88d083ee7b16597515462011381549cbdb7bf64e39a7e0d2c99b9ed57baa5cce5580b76de2bb3ed

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
